### ISSUE TITLE
Social button in the single post

### ISSUE THREAD

**Issue by omelki** [pro-freelancer/TOB#12]
We still have to change the social buttons in the single page:

https://cloud.githubusercontent.com/assets/7605683/6657020/5b993dbc-cb46-11e4-8810-419bfd2fc8d9.png

-They are here in svg: 
https://www.dropbox.com/sh/rhfr3k8xuspb2v2/AACki0Kvpl1ix55tgHJQd5aia?dl=0

**Comment by pro-freelancer** [comment]
Man, you should be aware of the links on the excert you added, I spend 2 hours till I detect the issue.
in the back office you didn't close corectly the a link <a href="http://www.newsobserver.com/living/food-drink/article10035503.htm in a good way wish lead to brok the site. Please be aware for next time, such errors are hard to detect.
