### ISSUE TITLE
ad overlapping

### ISSUE THREAD

**Issue by omelki** [pro-freelancer/TOB#13]
Check the below

https://cloud.githubusercontent.com/assets/7605683/6657266/c37188ce-cb4e-11e4-91c1-6c55a3e3840f.png

I thought we have dealt with this issue, this ad should be changed to 728x 90 when the window reaches 800px

**Comment by pro-freelancer** [comment]
possible from the javascript event, checking it.

**Comment by omelki** [comment]
Bro can we fix the press page first
I need to get going with the data entry

**Comment by pro-freelancer** [comment]
I fixed the issue by putting a condition in the scroller.
PS: in case you are in the big screen and resize it to mobile in browser, you need to reload the page to check that it is working. in mobile world, once loaded the condition will work, no switch like browser from big screen to low screen immediately. it will load on its proper condition and will work

**Comment by omelki** [comment]
OK great thx bro
