### ISSUE TITLE
Video Page

### ISSUE THREAD

**Issue by omelki** [pro-freelancer/TOB#14]
1- the url should be "www.tasteofbeirut.com/videos" and not "www.tasteofbeirut.com/the-show"

2- when I hover on recipe in the menu the dropdown menu should stick to the end of the navbar
check the image below
![screen shot 2015-03-17 at 11 59 57 pm](https://cloud.githubusercontent.com/assets/7605683/6698525/0aaf1bde-cd02-11e4-8730-a221b4aa06aa.png)

**Comment by pro-freelancer** [comment]
there was a replica of video permalink, so I named the videosold on permalink we are not using it anymore, and the-show to videos. Work perfectly.

**Comment by omelki** [comment]
now if you click on video in the menu it get me to an error page

**Comment by pro-freelancer** [comment]
Also renamed the page-show.php to page-videos and put a style sheet fix for the top menu by putting top:45px; issue closed

**Comment by omelki** [comment]
Not closed yet what you did isn't exactly what I have asked for

**Comment by omelki** [comment]
Nevertheless I have fixed it by modifying the css in the video page. I have undone your work (top:45px)
and added the following :

#wrapper .fusion-megamenu-wrapper.col-span-1{

  margin-bottom: 0px!important;
}

[class*='col-']{

padding-left:15px!important;
padding:0px;
margin-bottom: 40px;
}

Now we can close the issue (:
