### ISSUE TITLE
Next and Previous post in the video single post page

### ISSUE THREAD

**Issue by omelki** [pro-freelancer/TOB#15]
As shown in image below this post is the first one on the page so logically i should have beneath it the "next post" and not previous post, it seems they are all reversed.

(https://cloud.githubusercontent.com/assets/7605683/6698855/6496a4e8-cd05-11e4-87ba-e20fe5594e82.png)

**Comment by pro-freelancer** [comment]
the code is correct cause it is the same of next previous of the post. but the problem that the data on youtube.com are added on correct dates. and the postes on wordpress are published on new dates and not the same dates order. this is why as you can see from the wordpress the previous and next post are correct depends on the wordpress post records list wish differ from the youtube correct  spublished date.

Sugesstion. you should try to modify the date of post or the order of the posts from wordpress to have same list such youtube. I think we should add a plugin to make post order by dragging and dropping the post on correct order wish is not available by wordpress natively.

**Comment by omelki** [comment]
The above has been done by adding a plugin to reorder posts. it's now working like a charm.
