### ISSUE TITLE
Ticket to submit yo wp engine

### ISSUE THREAD

**Issue by omelki** [pro-freelancer/TOB#17]

**Comment by omelki** [comment]
1- For mirroring

2- and for the cron job too

**Comment by pro-freelancer** [comment]
While chating with the support, I found in the FAQ good links to read and do it our selves.
http://wpengine.com/support_categories/best-practices/
http://wpengine.com/support_categories/set-up-my-site/
http://wpengine.com/support_categories/multisite/
http://wpengine.com/support_categories/learn-about-the-platform/
http://wpengine.com/support_categories/general-wp-engine-info/

I will read them in the weekend so we will be ready for next week to have our platform.

**Comment by pro-freelancer** [comment]
http://wpengine.com/support/restore/

**Comment by pro-freelancer** [comment]
Terrance Kirby
You are now connected with a WP Engine technician. If there is already a ticket on this issue, please provide the ticket number. Thank you.
Hello, how may I help out today?
Joumana Accad
I just need some help in 2 things
first know when my system is taking backup of the database, it is getting huge, how I can reduce it
when a cron job is working on the system ? to take backup
that's it.
Terrance Kirby
Your backup times will be listed in the backup screen shown here: http://wpengine.com/support/restore/
Let me view your largest tables and see if I can't suggest something.
What installation is this on?
Joumana Accad
tasteofbeirut
1:35 am
Terrance Kirby
So here's the most to least problematic top 10 here:
+------------------+-----------------------+--------+
| DB | TableName | Rows |
+------------------+-----------------------+--------+
| wp_tasteofbeirut | wp_usermeta | 351878 |
| wp_tasteofbeirut | wp_commentmeta | 35142 |
| wp_tasteofbeirut | wp_comments | 28038 |
| wp_tasteofbeirut | wp_postmeta | 18046 |
| wp_tasteofbeirut | wp_term_relationships | 17154 |
| wp_tasteofbeirut | wp_users | 13886 |
| wp_tasteofbeirut | wp_subscribe2 | 13646 |
| wp_tasteofbeirut | wp_posts | 8457 |
| wp_tasteofbeirut | wp_term_taxonomy | 1286 |
| wp_tasteofbeirut | wp_terms | 1247 |
+------------------+-----------------------+--------+
Joumana Accad
what do you sugess ?
Terrance Kirby
Looking into fixes for bloated usermeta and commentmeta tables for you.
Joumana Accad
ok

**Comment by pro-freelancer** [comment]
Terrance Kirby
Do you have a bunch of legitimate users and comments? Also how many posts do you have to confirm?
Joumana Accad
I don't know, I'm the developer and not the owner.
what do you suggests !?
just try to clean the database in a way don't affect the confirm posts thing !
Terrance Kirby
Gotcha understood. I would consider checking a spam prevention plugins (you have akismet but only the free version, so may need another plugin) and seeing if there's a bunch of deletable spam in the DB. You can always backup first: http://wpengine.com/support/restore/
You have a ton of spam viewable here
http://tasteofbeirut…com/wp-admin/edit-comments.php
Joumana Accad
ok thanks you , I will check this matter later, have a nice day.

**Comment by omelki** [comment]
The akismet that we have is the pro version and not the free one
