### ISSUE TITLE
ADD the green avada colors in all links 

### ISSUE THREAD

**Issue by omelki** [pro-freelancer/TOB#20]
All links looks in posts are black - we need to change their colors in green - In her last post, there is example check it bel dashboard and then check it online. Thanks

**Comment by pro-freelancer** [comment]
ok will do this as it is an emergency now

**Comment by pro-freelancer** [comment]
The case that it seems there is a log of !important in the style.css of the avada-child themes, the previous developer was mistaken in over using the !important that made the issue harder to fix of another wasting hour.

solution was as follow:
at the top of style.css in the avada-child. added the following code.
.post-content a , .post-content a em, .post-content ul li a ,.post-content ul li a em {
	color:#6E9A1F!important;
}
.post-content a:hover, .post-content a:hover em,.post-content ul li a:hover,.post-content ul li a:hover em {
color:#A0CE4E!important;
}

wish made sure that the link and over are the colors of avada provided.
