### ISSUE TITLE
Add Custom Fields level  serving  recipe-time in recipie post content type

### ISSUE THREAD

**Issue by pro-freelancer** [pro-freelancer/TOB#23]

**Comment by pro-freelancer** [comment]
This was fixed by using the back office added plug in Custom Fields, 
Creating a rule on same posts-custom-fields to have a post type equal to recipe.
Issue closed.

**Comment by omelki** [comment]
Yes just checked it. Now we have to work on the permalinks for the
(previous and next post) as well as for the (related post)
