### ISSUE TITLE
  a) In the "previous/next" section, when it's the LAST POST I should only have previous post, same thing as for the FIRST POST of a category we should only have next post

### ISSUE THREAD

**Issue by pro-freelancer** [pro-freelancer/TOB#7]

**Comment by pro-freelancer** [comment]
I'm checking the id of the current post. if should be != last post id to show else it will show. Same thing will do with the previous if this post != the prevous post then display previous else don't show.

**Comment by omelki** [comment]
Tayyeb Wel 7all?
